/*
 https://leetcode.com/problems/remove-palindromic-subsequences/
1332. Remove Palindromic Subsequences
Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

approach: time complexity O(n)
if the string is empty then return 0, if the string is palindrome then return 1, else return 2 because we can remove all a's in one step and all b's in another step.ey observation (the actual solution)

The string contains only 'a' and 'b'.

So:

✅ Case 1: Entire string is a palindrome

→ Remove it in 1 step

✅ Case 2: Not a palindrome

→ Remove all 'a' in one step
→ Remove all 'b' in another step
→ Total = 2 steps
 */
public class LC_1332_removePalindromeSub {

    public int removePalindromeSub(String s) {
        StringBuilder st=new StringBuilder(s);
        if(s.equals(st.reverse().toString())) return 1;
        st=new StringBuilder();
        int n=s.length();
        for(int i=0;i<n;i++){
            if(s.charAt(i)!='a'){
                    st.append(s.charAt(i));
            }
        }
        if(st.length()>0) return 2;
        return 1;
    }
    
}
